# see https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  # Maintain dependencies for npm
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: tuesday
    target-branch: main
    assignees: [cicdbot]
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - javascript
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      npm-minor-patch:
        update-types:
          - minor
          - patch
        patterns:
          - "*"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: tuesday
    target-branch: main
    assignees: [cicdbot]
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - github_actions
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      actions:
        patterns:
          - "*"
