name: Dependabot auto-merge

on:
  workflow_run:
    workflows: ["Code Style", "Playwright", "CodeQL"]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    if: ${{ github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]' }}
    uses: sortie-ai/shared-workflows/.github/workflows/dependabot-merge.yml@d7d3eee35a3a49856abbb780d503eee59b5d5c6a # v1.0.0
    secrets:
      bot-token: ${{ secrets.CICDBOT_TOKEN }}
